# -*- coding: utf-8 -*-
"""
Dataset central — empresas/instituciones investigadas (RM-first, Chile).
Cada registro usa atributos CATEGÓRICOS que alimentan scoring.py.

Fuentes: investigación web 2023-2026 (reportes de sostenibilidad, memorias,
prensa, Mercado Público). Las cifras de flota son ESTIMACIONES salvo indicación;
se validan/depuran con la cuenta Apollo Professional de E-Auto.

NO se incluyen nombres de personas — solo cargos/áreas (la capa de contactos
verificados se extrae en Apollo).
"""

PRODUCTO = {
    "nombre": "Gecko EV48",
    "empresa": "E-Auto Global (Chile)",
    "tipo": "Van eléctrica comercial (carga y pasajeros)",
    "claims": [
        "Bajo costo operacional y excelente TCO",
        "Ahorro energético significativo frente a diésel",
        "Menor costo de mantenimiento",
        "Ideal para recorridos urbanos e interurbanos cortos y operaciones repetitivas",
    ],
}

# Supuestos por defecto del modelo de TCO/ahorro (editables en el dashboard)
TCO_DEFAULTS = {
    "km_anio": 35000,         # km/año por vehículo (operación urbana)
    "diesel_l_100": 12.0,     # consumo van diésel L/100km
    "precio_diesel": 1000,    # CLP/litro
    "ev_kwh_100": 25.0,       # consumo EV kWh/100km
    "precio_kwh": 150,        # CLP/kWh (tarifa comercial)
    "mant_diesel_km": 75,     # CLP/km mantención diésel
    "mant_ev_km": 35,         # CLP/km mantención EV
    "co2_diesel_kg_l": 2.68,  # kg CO2 por litro de diésel
    "co2_grid_kg_kwh": 0.30,  # kg CO2 por kWh (SEN Chile, aprox.)
}

# Cada empresa: atributos categóricos (driver del scoring) + texto.
EMPRESAS = [
    # ───────────────────── NIVEL 1 — RETAIL / SUPERMERCADOS / ALIMENTOS ─────────────────────
    {
        "nombre": "Walmart Chile (Líder)", "industria": "Supermercados / Retail", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota mixta grande (camiones + última milla)", "vans_estimadas": "Cientos (última milla e-commerce)",
        "flota_band": "grande", "urbano_level": "distribucion_mixta", "esg_level": "lider",
        "fin_level": "muy_alta", "adopcion_level": "alta", "acceso_level": "alto",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Reporte de Impacto Sostenible anual; rutas de bajas emisiones.",
        "compromiso_carbono": "Cero emisiones operaciones propias 2040; 100% energía renovable 2035; 50% de despachos e-commerce con vehículos de bajas emisiones al 2028.",
        "dolor": "Última milla e-commerce en expansión con presión de descarbonización y meta dura al 2028; hoy electrifica camiones (Foton) pero la capa de vans urbanas es un vacío.",
        "beneficio_ev48": "Vans EV48 para despacho domiciliario urbano: cierra el gap de la meta 2028 con menor TCO que la van diésel.",
        "decisores_titulos": ["Gerente Omnichannel Supply Chain", "Gerente de Innovación Supply Chain", "Gerente de Medio Ambiente y Sustentabilidad", "Gerente de Delivery Experience"],
        "senales": ["Meta 50% e-commerce bajas emisiones 2028", "50 camiones eléctricos Foton (mayor flota Sudamérica)", "Hub de carga ~1.200 kW en RM", "Inversión 2025 ~US$57M"],
        "fuentes": ["walmartchile.cl/proposito/sustentabilidad/distribucion-sustentable", "foton.cl (hub Sotraser/Copec/Andes Motor)"],
        "dato_calidad": "investigado",
        "justificacion": "Mayor retailer del país, ESG líder con meta dura de última milla 2028 y capacidad financiera enorme; el ángulo de vans urbanas complementa (no compite con) su flota de camiones eléctricos.",
    },
    {
        "nombre": "Cencosud (Jumbo / Santa Isabel)", "industria": "Supermercados / Retail", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de distribución grande (ASF Logística)", "vans_estimadas": "Cientos potenciales",
        "flota_band": "grande", "urbano_level": "distribucion_mixta", "esg_level": "medio",
        "fin_level": "muy_alta", "adopcion_level": "media", "acceso_level": "alto",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Reporte de Sostenibilidad anual; estrategia de cambio climático en 4 pilares.",
        "compromiso_carbono": "Estrategia climática publicada; año de carbono-neutralidad no explícito a nivel grupo.",
        "dolor": "Operación de despacho rápido (Spid 35, dark stores) creciente en RM; ya electrificó vans en filial Paris pero NO en supermercados Jumbo/Santa Isabel.",
        "beneficio_ev48": "Replicar el caso Paris (Electro Pipau / Copec Voltex) en el reparto de supermercados con vans EV48.",
        "decisores_titulos": ["Gerente de Estrategia y Sostenibilidad", "Gerente de Logística Supermercados", "Gerente regional Supply Chain", "Subgerente de Transportes (ASF Logística)"],
        "senales": ["Spid 35 y dark stores en RM", "EVs ya operando en filial Paris", "Ingresos 2024 ~$16,5 billones", "Inversión anunciada US$1.800M"],
        "fuentes": ["cencosud.com/sostenibilidad", "portalinnova.cl (Copec Voltex/Electro Pipau)"],
        "dato_calidad": "investigado",
        "justificacion": "Volumen y capacidad financiera de primer nivel; ya validó electromovilidad intra-grupo, lo que reduce riesgo de adopción. Brecha clara en supermercados.",
    },
    {
        "nombre": "SMU (Unimarc / Alvi / Mayorista 10)", "industria": "Supermercados / Retail", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de CD + e-commerce", "vans_estimadas": "Decenas-cientos",
        "flota_band": "mediana", "urbano_level": "distribucion_mixta", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Plan camino a carbono-neutralidad (alineado a meta país 2050); metas de energía renovable.",
        "compromiso_carbono": "Contribución a carbono-neutralidad país 2050; 40% suministro renovable 2025.",
        "dolor": "Despacho e-commerce de Unimarc.cl en sector oriente RM con plan de electromovilidad declarado pero sin proveedor EV confirmado.",
        "beneficio_ev48": "EV48 como flota base para el despacho de Unimarc.cl; proveedor aún abierto.",
        "decisores_titulos": ["Gerente de Supply Chain y Logística", "Gerente de Sostenibilidad", "Gerenta Corporativa de Personas y Sostenibilidad"],
        "senales": ["Plan de electromovilidad e-commerce (sector oriente RM)", "Centro robotizado de pedidos online", "Plan inversión US$300M"],
        "fuentes": ["smu.cl/noticias (carbono neutralidad)", "smu.cl/noticias (gestión ambiental)"],
        "dato_calidad": "investigado",
        "justificacion": "Tercer actor de supermercados con plan EV explícito y proveedor abierto: ventana de venta nueva.",
    },
    {
        "nombre": "Falabella / Sodimac / Tottus", "industria": "Retail / Mejoramiento del hogar", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de CD y última milla grande", "vans_estimadas": "Cientos (e-commerce y retiro)",
        "flota_band": "grande", "urbano_level": "distribucion_mixta", "esg_level": "lider",
        "fin_level": "muy_alta", "adopcion_level": "alta", "acceso_level": "alto",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Net Zero 2035 (alcances 1+2); Reporte de Sostenibilidad; Sodimac con meta propia.",
        "compromiso_carbono": "Grupo: Net Zero 2035, -65% emisiones 1+2 a 2030. Sodimac: carbono-neutral 2030 (transporte = 44% de sus GEI).",
        "dolor": "Transporte pesa fuerte en la huella de Sodimac; ya opera 8 camiones JAC pero la última milla liviana/urbana requiere vans.",
        "beneficio_ev48": "EV48 para última milla de e-commerce y reparto urbano de tiendas, alineado a su compromiso público con el Min. de Energía.",
        "decisores_titulos": ["Gerente de Sostenibilidad (grupo)", "Gerente de Control y Medioambiente", "Gerente de Supply Chain", "Gerente de Operación de CD"],
        "senales": ["Net Zero 2035 / Sodimac carbono-neutral 2030", "8 camiones JAC N55 ya operando", "Compromiso público-privado Min. Energía (24 camiones EV + cargadores)", "Nuevos CD Cerrillos/San Bernardo"],
        "fuentes": ["latercera.com (Net Zero 2035)", "energia.gob.cl/electromovilidad (compromiso flotas)"],
        "dato_calidad": "investigado",
        "justificacion": "ESG líder con metas duras y electrificación ya en marcha; capacidad financiera enorme y caso de uso urbano claro para vans.",
    },
    {
        "nombre": "Ripley", "industria": "Retail / Tienda por departamento", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota CD Redex + reparto", "vans_estimadas": "Decenas",
        "flota_band": "mediana", "urbano_level": "distribucion_mixta", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "'Compromiso R'; energía renovable en 62% de locales + CD (ISO 50001).",
        "compromiso_carbono": "Sin año de carbono-neutralidad público confirmado.",
        "dolor": "Despacho 90 min en sector oriente y reparto propio en RM, con menor madurez de electrificación que sus pares.",
        "beneficio_ev48": "Entrada EV en última milla propia con bajo TCO; oportunidad greenfield sin competidor instalado.",
        "decisores_titulos": ["Gerente de Operaciones", "Gerente de Logística (CD Redex)", "Equipo de Sostenibilidad ('Compromiso R')"],
        "senales": ["Despacho 90 min sector oriente RM", "Energía renovable 62% locales", "Vuelta a resultados positivos 2024 (+8,3% ingresos)"],
        "fuentes": ["colbun.cl (energía renovable Ripley)", "simple.ripley.cl (despacho)"],
        "dato_calidad": "investigado",
        "justificacion": "Reparto propio en RM y sin competidor EV instalado; ESG medio mantiene el score moderado pero el canal está limpio.",
    },
    {
        "nombre": "Coca-Cola Andina", "industria": "Bebidas / Distribución", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de distribución grande", "vans_estimadas": "Cientos (B2C/B2B)",
        "flota_band": "grande", "urbano_level": "distribucion_mixta", "esg_level": "alto",
        "fin_level": "muy_alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Compromiso SBTi (en validación); Memoria Anual Integrada; +44% energía renovable 2024.",
        "compromiso_carbono": "Meta 2030: -23% energía/litro vs 2018; net-zero sin año confirmado.",
        "dolor": "E-commerce B2C/B2B (miCoca-Cola.cl) y reparto desde Renca; ya electrificó intralogística (montacargas) pero no la última milla.",
        "beneficio_ev48": "Llevar la electrificación de la intralogística al reparto urbano con vans EV48.",
        "decisores_titulos": ["Gerente de Sostenibilidad / ESG", "Gerente de Operaciones / Supply Chain", "Gerente de Logística"],
        "senales": ["+200 montacargas eléctricos", "E-commerce miCoca-Cola.cl en RM", "Inversión 2025 US$240M", "SBTi en validación"],
        "fuentes": ["koandina.com (sostenibilidad)", "esghoy.cl (pilares ESG)"],
        "dato_calidad": "investigado",
        "justificacion": "Capacidad financiera alta y apetito EV demostrado (intralogística); la última milla es la brecha natural para vans.",
    },
    {
        "nombre": "CCU (Compañía Cervecerías Unidas)", "industria": "Bebidas / Distribución", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de reparto multi-región", "vans_estimadas": "Decenas EV + flota a convertir",
        "flota_band": "grande", "urbano_level": "distribucion_mixta", "esg_level": "lider",
        "fin_level": "muy_alta", "adopcion_level": "alta", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Visión Medioambiental 2030; Memoria Integrada; programa de electromovilidad maduro.",
        "compromiso_carbono": "Visión 2030: -50% emisiones GEI; ≥50% de la flota de camiones eléctrica al 2030.",
        "dolor": "Nuevo modelo de distribución con vehículos pequeños para zonas urbanas congestionadas; busca activamente unidades EV menores.",
        "beneficio_ev48": "EV48 calza con su 'modelo de vehículos 50% más pequeños' para Santiago Centro y zonas densas.",
        "decisores_titulos": ["Gerente de Operaciones", "Gerente de Logística", "Gerente de Sostenibilidad", "Comité de Dirección"],
        "senales": ["52 vehículos eléctricos de distribución (oct-2025)", "Meta ≥50% flota EV 2030", "Modelo de reparto urbano con vehículos pequeños", "Ingresos 2024 ~$2,9 billones"],
        "fuentes": ["ccu.cl/vision-medioambiental-2030", "ccu.cl (flota eléctrica)"],
        "dato_calidad": "investigado",
        "justificacion": "Programa EV explícitamente orientado a vehículos urbanos pequeños — encaje directo del EV48 — con meta dura 2030 y capacidad financiera fuerte.",
    },
    {
        "nombre": "Coca-Cola Embonor", "industria": "Bebidas / Distribución", "nivel": 1,
        "ubicacion": "Sur de Chile + Arica", "foco_rm": False,
        "veh_estimados": "Flota de reparto regional", "vans_estimadas": "Decenas",
        "flota_band": "grande", "urbano_level": "fuera_rm", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Lineamientos Sistema Coca-Cola; planta Re-Ciclar; 1er lugar Ranking Sostenibilidad 2024 (alimentos).",
        "compromiso_carbono": "Sin meta net-zero propia con año confirmado.",
        "dolor": "Distribución urbana en regiones (no RM); apetito EV aún no demostrado.",
        "beneficio_ev48": "Reparto urbano de bajo TCO en sus plazas regionales; oportunidad greenfield.",
        "decisores_titulos": ["Gerente de Sostenibilidad", "Gerente de Operaciones", "Gerente de Distribución"],
        "senales": ["Ranking Sostenibilidad #1 alimentos 2024", "Planta Re-Ciclar US$35M"],
        "fuentes": ["embonor.cl", "corresponsables.com (ranking 2024)"],
        "dato_calidad": "investigado",
        "justificacion": "Buen perfil de distribución pero fuera del foco RM; prioridad media para la fase 1 RM-first.",
    },
    {
        "nombre": "Soprole", "industria": "Alimentos / Lácteos (cadena de frío)", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota mixta (propia + operadores)", "vans_estimadas": "Decenas",
        "flota_band": "mediana", "urbano_level": "distribucion_mixta", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "fuerte", "potencial_elect": "alto",
        "programas_sost": "Reporte de Sostenibilidad; 'Sonrisa Circular'; descarbonización en curso.",
        "compromiso_carbono": "Estrategia de descarbonización; sin año net-zero confirmado.",
        "dolor": "Distribución de lácteos refrigerados desde CD Renca en RM; ya inició electrificación con FUSO (Copec Voltex/Kaufmann).",
        "beneficio_ev48": "Versión van refrigerada para tramos urbanos cortos donde el camión EV es excesivo; complemento a su flota EV existente.",
        "decisores_titulos": ["Gerente de Logística", "Gerente de Supply Chain", "Gerente de Sostenibilidad", "Gerente General"],
        "senales": ["4 camiones 100% eléctricos FUSO (nov-2025) en RM", "Cadena de frío láctea pionera EV", "Parte de Grupo Gloria"],
        "fuentes": ["copec.cl (camiones eléctricos Soprole)", "biobiochile.cl (camiones refrigerados EV)"],
        "dato_calidad": "investigado",
        "justificacion": "Apetito EV probado pero con competidor (FUSO/Kaufmann) ya instalado; el ángulo es la van liviana refrigerada para tramos urbanos.",
    },
    {
        "nombre": "Nestlé Chile", "industria": "Alimentos / Consumo masivo", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota baja emisión (EV + GNL)", "vans_estimadas": "Decenas (e-commerce)",
        "flota_band": "mediana", "urbano_level": "distribucion_mixta", "esg_level": "lider",
        "fin_level": "muy_alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Plan Net Zero; 100% electricidad renovable en fábricas Chile desde 2019.",
        "compromiso_carbono": "-50% GEI al 2030 y carbono-neutralidad al 2050.",
        "dolor": "CD e-commerce dedicado en Colina con entrega mismo día en RM; flota baja-emisión hoy son camiones (9 EV + 30 GNL), falta capa de vans.",
        "beneficio_ev48": "Vans EV48 para el reparto mismo día del CD Colina, completando su matriz baja-emisión.",
        "decisores_titulos": ["Gerente de Supply Chain", "Gerente de Logística / Transporte", "Gerente de Sostenibilidad"],
        "senales": ["CD e-commerce Colina (+2.000 pedidos/día, entrega mismo día)", "9 camiones EV + 30 GNL", "Net Zero 2050 / -50% 2030"],
        "fuentes": ["accionempresas.cl (Net Zero Nestlé)", "americaeconomia.com (CD e-commerce Colina)"],
        "dato_calidad": "investigado",
        "justificacion": "ESG líder, operación de reparto mismo día en RM y apetito EV demostrado; falta exactamente la categoría que vende E-Auto.",
    },
    {
        "nombre": "Carozzi", "industria": "Alimentos / Consumo masivo", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de distribución (propia + contratada)", "vans_estimadas": "Decenas",
        "flota_band": "mediana", "urbano_level": "distribucion_mixta", "esg_level": "alto",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Reporte Integrado; 100% energía renovable en centros Chile; Huella Chile.",
        "compromiso_carbono": "-50% intensidad de emisiones CO2e (alcance 1+2) al 2030 vs 2016.",
        "dolor": "Distribución B2B y canal tradicional desde CD Nos (RM) sin componente eléctrico — espacio greenfield.",
        "beneficio_ev48": "Electrificar el reparto urbano B2B con bajo TCO, mejorando la huella de transporte.",
        "decisores_titulos": ["Gerente de Logística", "Gerente de Transporte / Distribución", "Área de Sostenibilidad"],
        "senales": ["Meta -50% intensidad CO2e 2030", "CD modernizado en Nos (RM)", "Ingresos 2024 $1,56 billones / 11.037 empleados"],
        "fuentes": ["carozzicorp.com (reporte integrado)", "carozzicorp.com/Memoria-2024"],
        "dato_calidad": "investigado",
        "justificacion": "Meta de emisiones concreta y reparto urbano sin EV: prospecto greenfield con respaldo financiero.",
    },
    {
        "nombre": "Agrosuper", "industria": "Alimentos / Proteínas", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "~396 camiones sub-arrendados + reparto", "vans_estimadas": "Vía operadores",
        "flota_band": "tercerizada_gig", "urbano_level": "distribucion_mixta", "esg_level": "alto",
        "fin_level": "muy_alta", "adopcion_level": "baja", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Reporte Integrado; -16,7% huella de carbono; 69% energía renovable.",
        "compromiso_carbono": "Reducción de huella en curso; sin año net-zero confirmado.",
        "dolor": "Flota sub-arrendada (~396 camiones): la decisión de electrificar recae en operadores tercerizados, diluyéndola.",
        "beneficio_ev48": "Programa de electrificación con operadores (leasing/financiamiento) para el reparto urbano D2C (Tepido.cl).",
        "decisores_titulos": ["Gerente de Sucursales", "Gerente de Logística / Distribución", "Gerente de Sustentabilidad"],
        "senales": ["E-commerce D2C Tepido.cl en RM", "26 CDs nacionales (uno en RM 'SmartPicking')", "Ingresos 2024 US$4.276M"],
        "fuentes": ["agrosuper.cl (Reporte Sustentabilidad)", "df.cl (e-commerce/Tepido)"],
        "dato_calidad": "investigado",
        "justificacion": "Gran capacidad financiera y ESG sólido, pero la flota tercerizada baja la facilidad de adopción; requiere abordar a sus operadores.",
    },
    {
        "nombre": "Watt's", "industria": "Alimentos / Consumo masivo", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de distribución (9 CDs)", "vans_estimadas": "Decenas",
        "flota_band": "mediana", "urbano_level": "distribucion_mixta", "esg_level": "bajo",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Reporte de Sustentabilidad; APL Industria Láctea Sustentable; energía renovable.",
        "compromiso_carbono": "Sin año de carbono-neutralidad confirmado; vehículos a gas natural documentados.",
        "dolor": "Distribución de alimentos sin programa EV (solo GNV): máximo 'espacio en blanco'.",
        "beneficio_ev48": "Primer paso de electrificación en reparto urbano con bajo TCO y argumento ESG fresco.",
        "decisores_titulos": ["Gerente de Distribución / Logística", "Área de Sostenibilidad", "Gerencia de Operaciones"],
        "senales": ["9 CDs", "Flota a GNV (sin EV)", "Ventas 2024 US$653M / 2.806 colaboradores"],
        "fuentes": ["watts.cl (reporte sustentabilidad)", "watts.cl (resultados Q4 2024)"],
        "dato_calidad": "investigado",
        "justificacion": "Prospecto greenfield con respaldo financiero; ESG bajo reduce el score pero abre el argumento de 'primer EV'.",
    },

    # ───────────────────── NIVEL 1 — COURIER / LOGÍSTICA / E-COMMERCE ─────────────────────
    {
        "nombre": "Chilexpress", "industria": "Courier / Última milla", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "~750 vehículos última milla propios", "vans_estimadas": "200 EV (a 2026) + flota a convertir",
        "flota_band": "muy_grande", "urbano_level": "ultima_milla_rm", "esg_level": "lider",
        "fin_level": "alta", "adopcion_level": "alta", "acceso_level": "alto",
        "canal_compra": "venta_directa", "competidor_ev": "fuerte", "potencial_elect": "alto",
        "programas_sost": "Primera logística chilena con meta validada por SBTi; reportes públicos.",
        "compromiso_carbono": "Carbono-neutralidad al 2035 (alcances 1, 2 y 3).",
        "dolor": "Mayor flota EV de última milla del país, pero ya comprometida con Maxus (Kaufmann/Gama Mobility): el incumbente está instalado.",
        "beneficio_ev48": "Competir como segundo proveedor en su próxima ronda de expansión EV con mejor TCO; difícil desplazar al incumbente.",
        "decisores_titulos": ["Gerente de Operaciones / Última Milla", "Gerente de Sostenibilidad", "Gerente de Flota", "Gerente General"],
        "senales": ["Meta SBTi carbono-neutral 2035", "120→200 vans Maxus eDeliver (2026)", "90 EV operando en RM", "~25% de última milla electrificada"],
        "fuentes": ["ccs.cl (meta SBTi Chilexpress)", "autonoticias.cl (140 nuevos Maxus 2026)"],
        "dato_calidad": "investigado",
        "justificacion": "Score altísimo por flota/urbano/ESG, pero el competidor EV ya está instalado: probabilidad de compra ajustada a la baja en el corto plazo.",
    },
    {
        "nombre": "FedEx Chile (FedEx Express)", "industria": "Courier / Última milla", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "+880 vehículos propios", "vans_estimadas": "48 EV en 24 meses (plan)",
        "flota_band": "muy_grande", "urbano_level": "ultima_milla_rm", "esg_level": "lider",
        "fin_level": "muy_alta", "adopcion_level": "alta", "acceso_level": "alto",
        "canal_compra": "venta_directa", "competidor_ev": "fuerte", "potencial_elect": "alto",
        "programas_sost": "ISO 50001; Giro Limpio; GoGreen global.",
        "compromiso_carbono": "Carbono-neutral global 2040; 100% compras de vehículos de reparto cero emisiones a 2030.",
        "dolor": "Despliegue EV concreto pero ya con Maxus/Andes Motor como proveedor instalado (22% de la flota chica RM electrificada).",
        "beneficio_ev48": "Alternativa competitiva para el 78% restante de su flota chica; el incumbente Maxus está instalado.",
        "decisores_titulos": ["VP Operaciones Sudamérica", "Senior Manager Mantenimiento de Vehículos (Región Andina)", "Sostenibilidad corporativa"],
        "senales": ["Plan 48 EV en 24 meses", "22% de flota chica RM ya cero emisiones", "CD Pudahuel 14.000 m² (mayor de Sudamérica)", "20 cargadores ABB Copec Voltex"],
        "fuentes": ["newsroom.fedex.com (flota eléctrica Chile)", "newsroom.fedex.com (22% cero emisiones RM)"],
        "dato_calidad": "investigado",
        "justificacion": "Flota enorme y compromiso 2030/2040; el competidor instalado modera la probabilidad de venta nueva en el corto plazo.",
    },
    {
        "nombre": "Mercado Libre / Mercado Envíos", "industria": "E-commerce / Última milla", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": ">300 camionetas eléctricas en Chile", "vans_estimadas": ">300 (flota ~90% propia)",
        "flota_band": "muy_grande", "urbano_level": "ultima_milla_rm", "esg_level": "alto",
        "fin_level": "muy_alta", "adopcion_level": "alta", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Reporte de Impacto; Regenera América; bono sustentable.",
        "compromiso_carbono": "Compromisos de descarbonización a nivel grupo; US$150,8M en flota eléctrica regional.",
        "dolor": "Flota propia EV en fuerte expansión en RM con proveedor de vans NO especificado públicamente: puerta abierta.",
        "beneficio_ev48": "Proveer la próxima tanda de vans EV de su última milla con mejor TCO; proveedor aún no consolidado.",
        "decisores_titulos": ["Gerente de Operaciones (ML Chile)", "Director General (ML Chile/Perú/Ecuador)", "Líder de Logística / Mercado Envíos"],
        "senales": [">300 camionetas EV en Chile", "+100 vans EV (ago-2023)", "30 puntos de carga en Renca (Enel X Way)", "Inversión Chile US$400M"],
        "fuentes": ["news.mercadolibre.com (Reporte Impacto)", "diariosustentable.com (100 vans EV)"],
        "dato_calidad": "investigado",
        "justificacion": "Mayor flota EV de e-commerce con proveedor de vans abierto y crecimiento acelerado: oportunidad de gran volumen.",
    },
    {
        "nombre": "Correos de Chile", "industria": "Courier / Postal (estatal)", "nivel": 1,
        "ubicacion": "Nacional + RM", "foco_rm": True,
        "veh_estimados": "Flota propia nacional", "vans_estimadas": "Móviles eléctricos 'incipiente'",
        "flota_band": "grande", "urbano_level": "ultima_milla_rm", "esg_level": "alto",
        "fin_level": "restringida", "adopcion_level": "baja", "acceso_level": "bajo",
        "canal_compra": "mercado_publico", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Memoria Integrada; cuantificación de huella (alcances 1-3); +1.000 implementos sustentables.",
        "compromiso_carbono": "Alineado a carbono-neutralidad país 2050.",
        "dolor": "+700.000 envíos/día con flota propia, pero la capa de vans eléctricas es 'incipiente' (hoy bicis/triciclos/motos) y atraviesa crisis financiera 2025.",
        "beneficio_ev48": "Modernizar la última milla motorizada con vans EV de bajo costo operacional — clave dada la presión por eficiencia.",
        "decisores_titulos": ["Gerencia de Operaciones", "Gerencia de Sostenibilidad", "Gerencia General", "Directorio"],
        "senales": ["+700.000 envíos/día", "Flota de móviles EV 'incipiente'", "Crisis financiera 2025 (presión por eficiencia)", "Compra vía licitación pública"],
        "fuentes": ["esghoy.cl (Memoria Integrada Correos)", "energia.gob.cl (vehículos eléctricos Correos)"],
        "dato_calidad": "investigado",
        "justificacion": "Gran flota propia y operación urbana ideal, pero el ciclo de compra (licitación) y la fragilidad financiera bajan la probabilidad y velocidad.",
    },
    {
        "nombre": "Starken", "industria": "Courier / Última milla", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "~1.500 vehículos última milla (~500 vans propias)", "vans_estimadas": "~500 propias",
        "flota_band": "grande", "urbano_level": "ultima_milla_rm", "esg_level": "nulo",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "alto",
        "programas_sost": "Sin meta de carbono-neutralidad ni reporte de sostenibilidad público.",
        "compromiso_carbono": "No encontrado — espacio en blanco ESG.",
        "dolor": "Gran flota propia de última milla SIN ningún programa EV ni competidor instalado: la mayor oportunidad de venta nueva 'limpia'.",
        "beneficio_ev48": "Primer proveedor EV de su historia: posicionar EV48 como flota base con TCO y un argumento ESG que hoy no tienen.",
        "decisores_titulos": ["Gerente General", "Gerente de Operaciones", "Gerente de Logística"],
        "senales": ["~1.500 vehículos última milla / ~500 vans propias", "3er operador del mercado", "Sin programa EV ni competidor instalado", "Parte del Grupo Tur Bus"],
        "fuentes": ["starken.cl/distribucion", "Investigación FNE 2023 (ranking última milla)"],
        "dato_calidad": "investigado",
        "justificacion": "Flota grande y propia, canal directo y CERO competidor EV: aunque su ESG es bajo, es uno de los mejores objetivos de venta nueva del país.",
    },
    {
        "nombre": "Blue Express", "industria": "Courier / Última milla", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "2.261 vehículos (2024)", "vans_estimadas": "~30 EV (filial LoLlevo) + tercerizados",
        "flota_band": "tercerizada_gig", "urbano_level": "ultima_milla_rm", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Electromovilidad como pilar; 100% energía renovable en instalaciones; ESG vía Empresas Copec.",
        "compromiso_carbono": "Sin meta de carbono-neutralidad pública con año.",
        "dolor": "Líder de mercado (30-40% share) pero con flota mayormente SUBCONTRATADA (+1.000 transportistas): la decisión EV se diluye en terceros.",
        "beneficio_ev48": "Programa de electrificación para transportistas (financiamiento/leasing) + flota propia; entrada vía compromisos corporativos Copec.",
        "decisores_titulos": ["Gerente de Operaciones de Distribución", "Gerente de Personas y Sostenibilidad", "Supervisor de Flota"],
        "senales": ["41M envíos (2024), líder de mercado", "Master Plan US$100M con Copec", "Meta 1M paquetes/día a 2026", "≥15 furgones EV comprometidos"],
        "fuentes": ["latercera.com/pulso (líder última milla)", "energia.gob.cl (compromiso flotas)"],
        "dato_calidad": "investigado",
        "justificacion": "Volumen enorme pero modelo tercerizado: la facilidad de adopción y la propiedad de la flota bajan el score; mejor vía programa para transportistas.",
    },
    {
        "nombre": "99minutos", "industria": "E-commerce / Última milla", "nivel": 1,
        "ubicacion": "RM + V/VI regiones", "foco_rm": True,
        "veh_estimados": "Flota propia pequeña-mediana", "vans_estimadas": "Decenas",
        "flota_band": "pequena", "urbano_level": "ultima_milla_rm", "esg_level": "medio",
        "fin_level": "baja", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Servicio CO2Free; meta de flota propia 100% eléctrica (sin año).",
        "compromiso_carbono": "Meta declarada de flota 100% EV sin fecha comprometida.",
        "dolor": "Startup de última milla con perfil ESG afín y flota propia, pero escala y músculo financiero acotados.",
        "beneficio_ev48": "EV48 como columna de su promesa CO2Free; financiamiento será clave.",
        "decisores_titulos": ["Country Manager (Chile/Perú)", "Director de Operación Chile", "Chief Growth Officer"],
        "senales": ["~18.000 envíos/día en Chile", "Servicio CO2Free", "Meta flota 100% EV"],
        "fuentes": ["latamobility.com (EV última milla 99minutos)"],
        "dato_calidad": "investigado",
        "justificacion": "Encaje ESG/operacional fuerte, pero capacidad financiera baja; candidato a piloto con esquema de financiamiento.",
    },
    {
        "nombre": "DHL Express Chile", "industria": "Courier / Última milla", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota nacional", "vans_estimadas": "11 EV (2024) + plan",
        "flota_band": "grande", "urbano_level": "ultima_milla_rm", "esg_level": "alto",
        "fin_level": "muy_alta", "adopcion_level": "alta", "acceso_level": "alto",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "GoGreen; meta 60% de flota primera/última milla eléctrica a 2030.",
        "compromiso_carbono": "Cero emisiones netas 2050; 20% de flota local ya eléctrica (2024).",
        "dolor": "Compromiso firme y electrificación en curso (US$1,6M, 30 vehículos) pero con proveedor de vehículos AÚN no anunciado: puerta abierta.",
        "beneficio_ev48": "Posicionar EV48 como proveedor para su despliegue EV en RM, antes de que se consolide un incumbente.",
        "decisores_titulos": ["Country Manager DHL Express Chile", "Gerente de Operaciones / Flota", "Sostenibilidad (GoGreen)"],
        "senales": ["US$1,6M para 30 vehículos (jun-2024)", "Meta 60% flota EV 2030", "20% flota local ya eléctrica", "Proveedor de vehículos aún sin definir"],
        "fuentes": ["revistalogistec.com (DHL flota eléctrica Chile)"],
        "dato_calidad": "investigado",
        "justificacion": "Capacidad financiera y compromiso altos, con proveedor de vans aún abierto: ventana concreta de entrada.",
    },
    {
        "nombre": "PedidosYa Market", "industria": "E-commerce / Delivery (dark stores)", "nivel": 1,
        "ubicacion": "RM", "foco_rm": True,
        "veh_estimados": "Reparto gig + flota Market", "vans_estimadas": "Pocas (Market)",
        "flota_band": "tercerizada_gig", "urbano_level": "ultima_milla_rm", "esg_level": "alto",
        "fin_level": "media", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "medio",
        "programas_sost": "Carbono-neutral en Chile desde 2021; Memoria de Sostenibilidad (GRI).",
        "compromiso_carbono": "Carbono-neutral Chile (compensación) desde 2021.",
        "dolor": "El delivery principal es gig (sin flota); solo la unidad Market (dark stores) gestiona reparto propio.",
        "beneficio_ev48": "Vans EV48 para el reabastecimiento y reparto de PedidosYa Market en RM.",
        "decisores_titulos": ["Gerente General Chile", "Gerente de Operaciones PedidosYa Market", "Sostenibilidad"],
        "senales": ["Carbono-neutral Chile 2021", "Piloto motos/autos EV (sector oriente)", "PedidosYa Market dark stores"],
        "fuentes": ["emol.com (PedidosYa carbono-neutral)", "agenciase.org (micromovilidad EV)"],
        "dato_calidad": "investigado",
        "justificacion": "Buen perfil ESG, pero la flota está en el modelo gig; atacar específicamente la unidad Market.",
    },
    {
        "nombre": "Rappi Chile", "industria": "E-commerce / Delivery (gig)", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Modelo gig (sin flota propia)", "vans_estimadas": "N/A",
        "flota_band": "tercerizada_gig", "urbano_level": "ultima_milla_rm", "esg_level": "medio",
        "fin_level": "media", "adopcion_level": "baja", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "bajo",
        "programas_sost": "Iniciativas de movilidad sostenible para repartidores.",
        "compromiso_carbono": "Sin meta de flota propia (modelo gig).",
        "dolor": "Sin flota propia: el encaje es indirecto (programa de leasing EV para repartidores).",
        "beneficio_ev48": "Esquema de financiamiento/leasing de EV para repartidores aliados.",
        "decisores_titulos": ["Gerente General Chile", "Gerente de Operaciones"],
        "senales": ["Modelo gig", "Programas de movilidad para repartidores"],
        "fuentes": [],
        "dato_calidad": "estimacion",
        "justificacion": "Encaje débil por ausencia de flota propia; solo vía programa para repartidores. Prioridad baja.",
    },
    {
        "nombre": "Cornershop / Uber Eats", "industria": "E-commerce / Delivery (gig)", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Modelo gig (sin flota propia)", "vans_estimadas": "N/A",
        "flota_band": "tercerizada_gig", "urbano_level": "ultima_milla_rm", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "baja", "acceso_level": "bajo",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "bajo",
        "programas_sost": "Uber: cero emisiones 2040 (SBTi); Uber Green (pasajeros) en Santiago.",
        "compromiso_carbono": "Uber global cero emisiones 2040 (aplica a pasajeros, no a delivery).",
        "dolor": "Reparto 100% gig sin flota propia; el programa EV se enfoca en pasajeros.",
        "beneficio_ev48": "Encaje solo indirecto vía programa de leasing para shoppers.",
        "decisores_titulos": ["Gerente General Uber Eats Chile"],
        "senales": ["Uber Green +250 autos EV (pasajeros)", "Modelo gig en delivery"],
        "fuentes": ["uber.com/cl (Uber Green Chile)"],
        "dato_calidad": "estimacion",
        "justificacion": "Sin flota de reparto propia; encaje marginal. Prioridad baja.",
    },

    # ───────────────────── NIVEL 3 — SANITARIAS / ELÉCTRICAS / GAS / TELCO ─────────────────────
    {
        "nombre": "Aguas Andinas (+ Aguas Cordillera/Manquehue)", "industria": "Sanitaria", "nivel": 3,
        "ubicacion": "RM (Santiago)", "foco_rm": True,
        "veh_estimados": "Flota de servicio grande", "vans_estimadas": "23+ EV (desde 2019) + flota a convertir",
        "flota_band": "grande", "urbano_level": "servicio_urbano_rm", "esg_level": "alto",
        "fin_level": "muy_alta", "adopcion_level": "alta", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Reporte Integrado anual; economía circular; grupo Veolia.",
        "compromiso_carbono": "Estrategia de sostenibilidad de largo plazo (verificar año net-zero en Reporte Integrado).",
        "dolor": "Flota de cuadrillas 100% urbana en RM (lecturas, mantención de redes, emergencias); pionera EV (23 unidades desde 2019) pero falta escalar.",
        "beneficio_ev48": "Escalar su flota EV de servicio — caso de uso de recorrido repetitivo ideal — con vans de bajo TCO.",
        "decisores_titulos": ["Gerencia de Operaciones", "Gerencia de Sostenibilidad", "Jefatura de Flota / Logística"],
        "senales": ["23 vehículos EV operativos (2019)", "Operación 100% urbana RM", "Ahorro reportado ~94t CO2/año", "Grupo Veolia"],
        "fuentes": ["accionempresas.cl (flota EV Aguas Andinas)", "energia.gob.cl (furgones flota sanitaria)"],
        "dato_calidad": "investigado",
        "justificacion": "Caso de referencia: flota de servicio urbano en RM, ESG fuerte, capacidad financiera y apetito EV demostrado. Ideal para escalar.",
    },
    {
        "nombre": "Enel Distribución / Enel X", "industria": "Eléctrica (distribución)", "nivel": 3,
        "ubicacion": "RM (Santiago)", "foco_rm": True,
        "veh_estimados": "Flota técnica de cuadrillas grande", "vans_estimadas": "Decenas",
        "flota_band": "grande", "urbano_level": "servicio_urbano_rm", "esg_level": "lider",
        "fin_level": "muy_alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "fuerte", "potencial_elect": "alto",
        "programas_sost": "Compromisos de descarbonización del Grupo Enel; Enel X líder en electromovilidad.",
        "compromiso_carbono": "Descarbonización del Grupo Enel; metas globales.",
        "dolor": "Flota técnica propia significativa en RM; pero Enel X es el líder de electrificación de flotas (probable auto-abastecimiento) — es competidor/partner.",
        "beneficio_ev48": "Difícil como cliente puro (auto-abastece); más valioso como PARTNER de infraestructura de carga para los demás prospectos.",
        "decisores_titulos": ["Gerencia de Operaciones (Enel Distribución)", "Área de e-Mobility (Enel X)"],
        "senales": ["Enel X líder EV (468 estaciones, meta 1.200 a 2026)", "Aportó ~80% de buses eléctricos RED RM", "Flota técnica propia de cuadrillas"],
        "fuentes": ["enelx.com/cl (flotas EV)", "enelx.com/cl (flota camiones Unilever)"],
        "dato_calidad": "investigado",
        "justificacion": "Score alto por perfil, pero como comprador su apetito lo cubre Enel X internamente: mejor tratarlo como aliado de carga.",
    },
    {
        "nombre": "CGE", "industria": "Eléctrica / Gas (distribución)", "nivel": 3,
        "ubicacion": "RM + Nacional (166 comunas)", "foco_rm": True,
        "veh_estimados": "Flota técnica nacional grande", "vans_estimadas": "Decenas-cientos",
        "flota_band": "grande", "urbano_level": "servicio_urbano_rm", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "medio",
        "programas_sost": "Mejora de calidad de servicio; foco en electrolineras públicas (no flota propia).",
        "compromiso_carbono": "Sin meta de carbono-neutralidad confirmada (verificar en cge.cl).",
        "dolor": "Grandes cuadrillas de mantención de redes en RM y 166 comunas, pero su foco EV está en electrolineras públicas, no en su flota.",
        "beneficio_ev48": "Electrificar la flota de cuadrillas con vans de servicio de bajo TCO — coherente con su negocio energético.",
        "decisores_titulos": ["Gerencia General", "Gerencia de Operaciones (terreno)", "Área de Sostenibilidad"],
        "senales": ["~3M de clientes / 166 comunas", "Electrolineras públicas en expansión", "Inversiones 2023 $214.799M"],
        "fuentes": ["cge.cl", "energia.gob.cl (compromiso flotas)"],
        "dato_calidad": "investigado",
        "justificacion": "Flota técnica grande con cobertura RM; ESG medio y foco actual en carga pública moderan el score.",
    },
    {
        "nombre": "Entel", "industria": "Telecomunicaciones", "nivel": 3,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de cuadrillas técnicas", "vans_estimadas": "Decenas",
        "flota_band": "mediana", "urbano_level": "servicio_urbano_rm", "esg_level": "alto",
        "fin_level": "muy_alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "alto",
        "programas_sost": "Reporte de Sostenibilidad 2024; estrategia 'Conciencia en todas' 2024-2030.",
        "compromiso_carbono": "Carbono-neutralidad a 2050.",
        "dolor": "Cuadrillas de instalación/mantención en RM sin programa de electrificación de flota documentado: greenfield con ESG sólido.",
        "beneficio_ev48": "Primer paso de electrificación de su flota técnica, con argumento ESG ya instalado en su estrategia.",
        "decisores_titulos": ["Gerencia de Sostenibilidad", "Gerencia de Operaciones de Red", "Logística / Flota"],
        "senales": ["Reporte de Sostenibilidad 2024", "Carbono-neutral 2050", "Cuadrillas técnicas urbanas RM", "Sin programa EV de flota (greenfield)"],
        "fuentes": ["entel.cl (reporte sostenibilidad 2024)", "informacioncorporativa.entel.cl"],
        "dato_calidad": "investigado",
        "justificacion": "Capacidad financiera muy alta, ESG sólido y flota técnica urbana sin competidor EV: greenfield atractivo.",
    },
    {
        "nombre": "Movistar / Telefónica Chile", "industria": "Telecomunicaciones", "nivel": 3,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota técnica (30% ya en electromovilidad)", "vans_estimadas": "70% remanente por electrificar",
        "flota_band": "mediana", "urbano_level": "servicio_urbano_rm", "esg_level": "alto",
        "fin_level": "alta", "adopcion_level": "alta", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Política energética; meta 100% energía renovable instalaciones 2030; sello Eco Smart.",
        "compromiso_carbono": "Grupo Telefónica net zero 2040; huella reducida 95% (2022 vs 2015).",
        "dolor": "Ya electrificó ~30% de su flota: el 70% remanente es una oportunidad concreta y cuantificada.",
        "beneficio_ev48": "Proveer la siguiente fase de electrificación del 70% restante de la flota técnica.",
        "decisores_titulos": ["Gerencia de Sostenibilidad", "Gerencia de Operaciones de Red", "Logística / Flota"],
        "senales": ["30% de flota ya en electromovilidad", "Net zero 2040", "Meta 100% renovable instalaciones 2030"],
        "fuentes": ["telefonica.cl (política energética Movistar)"],
        "dato_calidad": "investigado",
        "justificacion": "Apetito EV ya demostrado (30%) con un 70% remanente identificado: pipeline cuantificado y de adopción fácil.",
    },
    {
        "nombre": "WOM", "industria": "Telecomunicaciones", "nivel": 3,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota técnica (probable tercerizada)", "vans_estimadas": "Pocas propias",
        "flota_band": "pequena", "urbano_level": "servicio_urbano_rm", "esg_level": "bajo",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Reporte de Sostenibilidad (4º año); ISO 50001 en data centers/antenas.",
        "compromiso_carbono": "Sin meta explícita de carbono-neutralidad; foco en residuos/energía.",
        "dolor": "Flota técnica probablemente tercerizada y sin foco en movilidad: menor prioridad.",
        "beneficio_ev48": "Electrificar la operación técnica si decide internalizar flota.",
        "decisores_titulos": ["Área de Sostenibilidad", "Operaciones"],
        "senales": ["Reporte de Sostenibilidad anual", "ISO 50001 data centers"],
        "fuentes": ["sobrenosotros.wom.cl/sostenibilidad"],
        "dato_calidad": "investigado",
        "justificacion": "ESG y flota propia débiles; prioridad media-baja dentro del segmento telco.",
    },
    {
        "nombre": "Claro / VTR (ClaroVTR)", "industria": "Telecomunicaciones", "nivel": 3,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Gran parque de cuadrillas (fijo + móvil)", "vans_estimadas": "Decenas-cientos",
        "flota_band": "grande", "urbano_level": "servicio_urbano_rm", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "alto",
        "programas_sost": "Reporte de Sostenibilidad integrado (Claro+VTR); 'Sostenibilidad Inteligente'.",
        "compromiso_carbono": "Reducir 50% emisiones GEI a 2030.",
        "dolor": "Uno de los mayores parques de cuadrillas de terreno entre telcos (VTR cable/fibra), sin programa EV: greenfield grande.",
        "beneficio_ev48": "Electrificar el numeroso parque de cuadrillas urbanas con vans de servicio.",
        "decisores_titulos": ["Área de Sostenibilidad", "Operaciones de Red", "Logística / Flota"],
        "senales": ["Meta -50% GEI 2030", "Gran parque de cuadrillas urbanas RM", "Sin programa EV (greenfield)"],
        "fuentes": ["clarochile.cl/institucional/sostenibilidad"],
        "dato_calidad": "investigado",
        "justificacion": "Flota de servicio urbana grande sin competidor EV; ESG medio mantiene el score moderado pero el volumen es atractivo.",
    },
    {
        "nombre": "GASCO", "industria": "Gas (distribución)", "nivel": 3,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de reparto de cilindros", "vans_estimadas": "Decenas",
        "flota_band": "grande", "urbano_level": "servicio_urbano_rm", "esg_level": "alto",
        "fin_level": "alta", "adopcion_level": "alta", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Posicionamiento de transición energética; Gasco Luz; reportes de sostenibilidad.",
        "compromiso_carbono": "Posicionamiento hacia carbono-neutralidad (verificar año).",
        "dolor": "Reparto domiciliario de cilindros (recorrido urbano repetitivo) con primer camión EV (Voltera) ya operando: apetito probado.",
        "beneficio_ev48": "Vans EV48 para el reparto urbano de cilindros y servicios, escalando su piloto EV.",
        "decisores_titulos": ["Gerencia de Operaciones / Logística de reparto", "Área de Sostenibilidad"],
        "senales": ["Primer camión 100% eléctrico de reparto (Voltera, 2021)", "Gasco Luz (baja en carbono)", "Reparto urbano repetitivo de cilindros"],
        "fuentes": ["reportesostenible.cl (camión eléctrico Gasco)"],
        "dato_calidad": "investigado",
        "justificacion": "Recorrido urbano repetitivo ideal y apetito EV demostrado; capacidad financiera sólida.",
    },
    {
        "nombre": "Metrogas", "industria": "Gas (distribución por red)", "nivel": 3,
        "ubicacion": "RM (Santiago)", "foco_rm": True,
        "veh_estimados": "Flota de cuadrillas de red", "vans_estimadas": "Decenas",
        "flota_band": "mediana", "urbano_level": "servicio_urbano_rm", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Reporte de Sustentabilidad (verificar datos vs filial argentina).",
        "compromiso_carbono": "Meta de carbono-neutralidad Chile no confirmada.",
        "dolor": "Cuadrillas de instalación/mantención de red de gas en la RM, operación urbana intensiva, sin programa EV.",
        "beneficio_ev48": "Electrificar las cuadrillas urbanas con vans de servicio de bajo TCO.",
        "decisores_titulos": ["Gerencia de Operaciones", "Área de Sostenibilidad", "Logística"],
        "senales": ["Principal distribuidora de gas natural por red RM", "Cuadrillas urbanas intensivas"],
        "fuentes": ["tercertiempo.news (reporte sustentabilidad Metrogas)"],
        "dato_calidad": "investigado",
        "justificacion": "Operación urbana RM clara y sin competidor EV; datos ESG por confirmar moderan el score.",
    },
    {
        "nombre": "Esval / Aguas del Valle", "industria": "Sanitaria", "nivel": 3,
        "ubicacion": "Valparaíso / Coquimbo", "foco_rm": False,
        "veh_estimados": "Flota de servicio regional", "vans_estimadas": "Decenas",
        "flota_band": "grande", "urbano_level": "fuera_rm", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "alto",
        "programas_sost": "Great Place To Work 2024; reporte de sostenibilidad por confirmar.",
        "compromiso_carbono": "No localizado (verificar en esval.cl).",
        "dolor": "Perfil operativo idéntico a Aguas Andinas (cuadrillas, lecturas, redes) pero fuera de la RM.",
        "beneficio_ev48": "Replicar el caso Aguas Andinas en Valparaíso/Coquimbo; greenfield sin competidor.",
        "decisores_titulos": ["Gerencia de Operaciones", "Área de Sostenibilidad"],
        "senales": [">980 empleados", "Cuadrillas de servicio regional", "Sin programa EV (greenfield)"],
        "fuentes": ["esval.cl (filial Aguas del Valle)"],
        "dato_calidad": "investigado",
        "justificacion": "Excelente perfil operativo pero fuera del foco RM; prioridad para expansión a regiones.",
    },

    # ───────────────────── NIVEL 2 — SALUD / UNIVERSIDADES / AEROPUERTO / TRANSPORTE ─────────────────────
    {
        "nombre": "Clínica Las Condes", "industria": "Salud / Clínica", "nivel": 2,
        "ubicacion": "RM (sector oriente)", "foco_rm": True,
        "veh_estimados": "Flota de ambulancias + apoyo", "vans_estimadas": "Pocas",
        "flota_band": "muy_pequena", "urbano_level": "distribucion_mixta", "esg_level": "bajo",
        "fin_level": "media", "adopcion_level": "baja", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "bajo",
        "programas_sost": "Sin compromiso formal de carbono-neutralidad verificable.",
        "compromiso_carbono": "No encontrado.",
        "dolor": "Flota chica (ambulancias/apoyo) y proceso de reestructuración + cambio de control (Indisa/EuroAmérica) que puede pausar CAPEX.",
        "beneficio_ev48": "Vans para traslados de personal/insumos urbanos; oportunidad limitada por escala.",
        "decisores_titulos": ["Gerencia de Operaciones", "Gerencia de Administración y Finanzas", "Abastecimiento"],
        "senales": ["Cambio de control 2025 (posible pausa CAPEX)", "Renovación parcial de flota"],
        "fuentes": ["clinicalascondes.cl", "latercera.com"],
        "dato_calidad": "investigado",
        "justificacion": "Escala de flota baja y timing de CAPEX adverso; prioridad baja en el corto plazo.",
    },
    {
        "nombre": "Clínica Alemana", "industria": "Salud / Clínica", "nivel": 2,
        "ubicacion": "RM (Vitacura)", "foco_rm": True,
        "veh_estimados": "Flota de rescate + apoyo", "vans_estimadas": "Pocas",
        "flota_band": "muy_pequena", "urbano_level": "distribucion_mixta", "esg_level": "lider",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Reporte de Sostenibilidad desde 2015; sellos HuellaChile (cuantificación y reducción); líder Merco ESG clínicas.",
        "compromiso_carbono": "Carbono-neutralidad al 2050; -39% emisiones GEI 2021-2024.",
        "dolor": "Mayor madurez ESG del sector salud pero sin foco en movilidad: oportunidad greenfield de imagen.",
        "beneficio_ev48": "Vans EV para traslados y servicios, alineadas a su liderazgo ESG (argumento reputacional fuerte).",
        "decisores_titulos": ["Gerencia General", "Gerencia de Administración y Finanzas", "Gerencia de Abastecimiento", "Gerencia de Operaciones"],
        "senales": ["Carbono-neutral 2050 / -39% GEI", "Sellos HuellaChile", "Estación de carga EV en campus Vitacura"],
        "fuentes": ["reporte-sostenibilidad.clinicaalemana.cl", "latercera.com"],
        "dato_calidad": "investigado",
        "justificacion": "ESG líder en salud con receptividad reputacional alta; la flota chica limita el volumen pero abre el caso simbólico.",
    },
    {
        "nombre": "RedSalud", "industria": "Salud / Red de clínicas", "nivel": 2,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de apoyo (no pública)", "vans_estimadas": "Pocas-decenas",
        "flota_band": "pequena", "urbano_level": "distribucion_mixta", "esg_level": "bajo",
        "fin_level": "media", "adopcion_level": "baja", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "bajo",
        "programas_sost": "Sostenibilidad genérica 'Desafío 2025'; reducción de huella hídrica.",
        "compromiso_carbono": "Sin meta GEI cuantificada pública.",
        "dolor": "Red amplia (44 establecimientos) con flota de apoyo difusa y ESG poco maduro.",
        "beneficio_ev48": "Vans para logística inter-recintos y traslados; oportunidad incipiente.",
        "decisores_titulos": ["Gerencia de Red (Operacional y Procesos Logísticos)", "Abastecimiento centralizado"],
        "senales": ["44 establecimientos nacionales", "Organigrama 'RedSalud 2030' centraliza logística", "Filial de ILC (CChC)"],
        "fuentes": ["redsalud.cl", "ilcinversiones.cl"],
        "dato_calidad": "investigado",
        "justificacion": "Escala institucional grande pero ESG y flota propia poco desarrollados; prioridad media-baja.",
    },
    {
        "nombre": "Banmédica (Santa María / Dávila / Vidaintegra)", "industria": "Salud / Red de clínicas", "nivel": 2,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de rescate + apoyo", "vans_estimadas": "Pocas-decenas",
        "flota_band": "pequena", "urbano_level": "distribucion_mixta", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "baja", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Informe de Impacto en Sostenibilidad; Santa María ISO 50001; Dávila 'Green Hospital'.",
        "compromiso_carbono": "Sin meta net-zero a nivel holding confirmada.",
        "dolor": "Red de clínicas con iniciativas de eficiencia energética, sin programa de movilidad EV; cambio de control (Patria) puede pausar CAPEX.",
        "beneficio_ev48": "Vans EV para la red ambulatoria (Vidaintegra, 17 centros RM) y logística inter-recintos.",
        "decisores_titulos": ["Gerencia de Abastecimiento Corporativo", "Gerencia de Operaciones"],
        "senales": ["Santa María ISO 50001", "Dávila Green Hospital Oro (2025)", "Vidaintegra 17 centros RM", "Cambio de control Patria (1T 2026)"],
        "fuentes": ["empresasbanmedica.cl", "davila.cl/sostenibilidad"],
        "dato_calidad": "investigado",
        "justificacion": "Red amplia con cierta madurez energética; flota de apoyo modesta y timing de CAPEX por confirmar.",
    },
    {
        "nombre": "Pontificia Universidad Católica (UC)", "industria": "Universidad", "nivel": 2,
        "ubicacion": "RM (4 campus)", "foco_rm": True,
        "veh_estimados": "Flota propia muy pequeña (0,1% huella) + buses tercerizados", "vans_estimadas": "Pocas propias",
        "flota_band": "muy_pequena", "urbano_level": "distribucion_mixta", "esg_level": "lider",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Estrategia de Acción Climática (2023); Dirección de Sustentabilidad.",
        "compromiso_carbono": "Carbono-neutralidad al 2038 (primera IES chilena en declararlo).",
        "dolor": "Meta carbono-neutral 2038 ambiciosa, pero flota propia mínima (el grueso de la huella es transporte/commuting).",
        "beneficio_ev48": "Vans EV para servicios de campus y traslados inter-sede + buses de acercamiento (hoy tercerizados).",
        "decisores_titulos": ["Vicerrectoría de Asuntos Económicos y Administrativos", "Dirección de Gestión de Campus", "Dirección de Sustentabilidad"],
        "senales": ["Carbono-neutral 2038", "4 campus en RM", "Estrategia de Acción Climática 2023", "Buses de acercamiento tercerizados"],
        "fuentes": ["sustentable.uc.cl (estrategia 2023)", "uc.cl (carbono neutral 2038)"],
        "dato_calidad": "investigado",
        "justificacion": "ESG líder y compra directa (privada), pero la flota propia es mínima; el ángulo es servicios de campus + buses de acercamiento.",
    },
    {
        "nombre": "Universidad de Chile", "industria": "Universidad (estatal)", "nivel": 2,
        "ubicacion": "RM (5 campus)", "foco_rm": True,
        "veh_estimados": "Flota propia pequeña", "vans_estimadas": "Pocas",
        "flota_band": "pequena", "urbano_level": "servicio_urbano_rm", "esg_level": "alto",
        "fin_level": "media", "adopcion_level": "baja", "acceso_level": "bajo",
        "canal_compra": "mercado_publico", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "APL II Educación Superior; Plan de Sustentabilidad 2025-2028.",
        "compromiso_carbono": "Carbono-neutralidad al 2050.",
        "dolor": "5 campus dispersos en RM con traslados inter-sede, pero la compra es vía Mercado Público (ciclo largo).",
        "beneficio_ev48": "Vans EV para traslados inter-campus y servicios; vía convenio marco/licitación.",
        "decisores_titulos": ["Vicerrectoría de Asuntos Económicos y Gestión Institucional", "Dirección de Servicios e Infraestructura", "Comité por la Sustentabilidad"],
        "senales": ["Carbono-neutral 2050", "5 campus en RM", "APL II Educación Superior"],
        "fuentes": ["uchile.cl/sustentabilidad", "uchile.cl/vaegi"],
        "dato_calidad": "investigado",
        "justificacion": "ESG sólido y necesidad inter-campus, pero el canal Mercado Público y el acceso difuso bajan velocidad y score.",
    },
    {
        "nombre": "Universidad de Santiago (USACH)", "industria": "Universidad (estatal)", "nivel": 2,
        "ubicacion": "RM (campus único)", "foco_rm": True,
        "veh_estimados": "Flota propia muy pequeña", "vans_estimadas": "Pocas",
        "flota_band": "muy_pequena", "urbano_level": "distribucion_mixta", "esg_level": "alto",
        "fin_level": "media", "adopcion_level": "baja", "acceso_level": "bajo",
        "canal_compra": "mercado_publico", "competidor_ev": "ninguno", "potencial_elect": "bajo",
        "programas_sost": "Política de Sostenibilidad; 2º APL Red Campus Sustentable; Plan de Movilidad 2025.",
        "compromiso_carbono": "Carbono-neutralidad al 2050.",
        "dolor": "Campus único compacto → poca necesidad de vans; el plan de movilidad prioriza peatón/bici.",
        "beneficio_ev48": "Vans para servicios internos puntuales; encaje limitado.",
        "decisores_titulos": ["Dirección de Administración y Finanzas (Adquisiciones)", "Área de Sostenibilidad"],
        "senales": ["Carbono-neutral 2050", "Plan de Movilidad 2025 (peatón/bici)", "Campus único Estación Central"],
        "fuentes": ["usach.cl (política sostenibilidad)", "sostenibilidad.usach.cl (plan movilidad)"],
        "dato_calidad": "investigado",
        "justificacion": "ESG fuerte pero baja necesidad de vans (campus único) y canal Mercado Público; prioridad media-baja.",
    },
    {
        "nombre": "Universidad Andrés Bello (UNAB)", "industria": "Universidad", "nivel": 2,
        "ubicacion": "RM (6 campus)", "foco_rm": True,
        "veh_estimados": "Flota + ~25 shuttles/día (tercerizados)", "vans_estimadas": "Decenas potenciales",
        "flota_band": "pequena", "urbano_level": "servicio_urbano_rm", "esg_level": "alto",
        "fin_level": "alta", "adopcion_level": "alta", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "alto",
        "programas_sost": "Hoja de ruta carbono-neutral; 100% energía limpia; Pacto Global ONU; THE Impact Ranking #1 Chile 2025.",
        "compromiso_carbono": "Carbono-neutralidad a 2038; Plan de Movilidad Sostenible que dice explícitamente 'electrificar la flota institucional'.",
        "dolor": "6 campus en RM con ~25 servicios de acercamiento diarios hoy diésel; plan explícito de electrificar flota, sin compra aún.",
        "beneficio_ev48": "Vans/minibuses EV48 para los buses de acercamiento inter-campus — caso de uso directo del plan.",
        "decisores_titulos": ["Vicerrectoría Económica (Adquisiciones)", "Prorrectoría / Dirección de Sostenibilidad", "Operaciones"],
        "senales": ["Plan de Movilidad: 'electrificar flota institucional'", "Anfitriona Acuerdo Electromovilidad 2026", "6 campus RM / ~25 shuttles diésel/día", "Carbono-neutral 2038"],
        "fuentes": ["sostenibilidad.unab.cl", "eldinamo.cl (plan movilidad UNAB)"],
        "dato_calidad": "investigado",
        "justificacion": "Única universidad con plan que dice 'electrificar la flota', compra directa (privada) y caso de uso de shuttles claro: prospecto fuerte.",
    },
    {
        "nombre": "Nuevo Pudahuel (Aeropuerto AMB Santiago)", "industria": "Aeropuerto / Concesión", "nivel": 2,
        "ubicacion": "RM (Pudahuel)", "foco_rm": True,
        "veh_estimados": "GSE + shuttles + minibuses (concesión)", "vans_estimadas": "Decenas (minibuses/servicios)",
        "flota_band": "mediana", "urbano_level": "servicio_urbano_rm", "esg_level": "lider",
        "fin_level": "muy_alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "mixto", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Plan 'Aeropuerto Verde' (MMA); Airport Carbon Accreditation; 100% energía renovable (ENGIE); consorcio ADP/VINCI.",
        "compromiso_carbono": "Net-zero a 2050; -40% CO2 a 2030.",
        "dolor": "Récord de 26M pasajeros; ya licita buses/minibuses con cero emisiones, pero la flota interna de servicio (GSE/vans) tiene espacio sin cubrir.",
        "beneficio_ev48": "Vans EV para traslados de personal, shuttle entre terminales y servicios de rampa, alineadas a su plan verde.",
        "decisores_titulos": ["Gerencia de Operaciones", "Gerencia de Sostenibilidad / Medio Ambiente", "Gerencia Comercial"],
        "senales": ["Net-zero 2050 / -40% 2030", "Licitación minibuses cero emisiones (Transvip a 2031)", "Primeros buses eléctricos de aproximación LATAM", "Plan Aeropuerto Verde"],
        "fuentes": ["mma.gob.cl (Aeropuerto Verde)", "mtt.gob.cl (buses aproximación)"],
        "dato_calidad": "investigado",
        "justificacion": "ESG líder y capacidad financiera muy alta, con apetito EV demostrado; la flota interna de servicio es la brecha para vans.",
    },
    {
        "nombre": "Metro de Santiago", "industria": "Transporte (empresa pública)", "nivel": 2,
        "ubicacion": "RM (Santiago)", "foco_rm": True,
        "veh_estimados": "Flota de apoyo/mantenimiento terrestre", "vans_estimadas": "Decenas",
        "flota_band": "mediana", "urbano_level": "servicio_urbano_rm", "esg_level": "lider",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "mercado_publico", "competidor_ev": "ninguno", "potencial_elect": "alto",
        "programas_sost": "Plan de Sostenibilidad ESG; Sello de Neutralización HuellaChile; 100% matriz energética renovable.",
        "compromiso_carbono": "Carbono-neutralidad operacional 2025 (lograda).",
        "dolor": "Carbono-neutral en operación ferroviaria, pero su flota terrestre de apoyo (camionetas/vans entre estaciones y talleres) no tiene electrificación pública.",
        "beneficio_ev48": "Electrificar la flota terrestre de mantenimiento/supervisión, coherente con su liderazgo en carbono-neutralidad.",
        "decisores_titulos": ["Dirección de Abastecimiento (Adquisiciones)", "Gerencia de Operaciones y Mantenimiento", "Área de Sostenibilidad"],
        "senales": ["Carbono-neutral operación 2025", "7 talleres / flota de apoyo terrestre", "Compra vía Mercado Público + portal propio"],
        "fuentes": ["metro.cl (plan sostenibilidad)", "metro.cl/licitaciones"],
        "dato_calidad": "investigado",
        "justificacion": "Liderazgo ESG y flota de apoyo greenfield; el canal Mercado Público modera la velocidad pero el caso es sólido.",
    },

    # ───────────────────── NIVEL 3 — MUNICIPIOS RM ─────────────────────
    {
        "nombre": "Municipalidad de Vitacura", "industria": "Municipalidad", "nivel": 3,
        "ubicacion": "RM (Vitacura)", "foco_rm": True,
        "veh_estimados": "Flota municipal (~45% ya eléctrica)", "vans_estimadas": "Por electrificar (seguridad/servicios)",
        "flota_band": "pequena", "urbano_level": "servicio_urbano_rm", "esg_level": "lider",
        "fin_level": "media", "adopcion_level": "alta", "acceso_level": "medio",
        "canal_compra": "mercado_publico", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Sello Comuna Energética 'Avanzada' (nivel máximo); PACCC con pilar de electromovilidad.",
        "compromiso_carbono": "Carbono-neutral comunal a 2050; RFI EV en Mercado Público (2023).",
        "dolor": "~45% de la flota ya es eléctrica; el ~55% restante (seguridad ciudadana, servicios) es la oportunidad inmediata.",
        "beneficio_ev48": "Completar la electrificación de la flota operativa (vans de seguridad/servicios) con bajo TCO.",
        "decisores_titulos": ["SECPLA (licitaciones)", "Dirección de Administración y Finanzas", "Dirección de Aseo y Ornato"],
        "senales": ["~45% flota ya eléctrica", "Sello Comuna Energética 'Avanzada'", "RFI EV en Mercado Público (2023)", "Camión recolector EV (Maxus/Enel X)"],
        "fuentes": ["vitacura.cl (Comuna Energética)", "agenciase.org (RFI flota EV)"],
        "dato_calidad": "investigado",
        "justificacion": "Máxima madurez EV municipal y apetito demostrado; el canal Mercado Público es el único freno relativo.",
    },
    {
        "nombre": "Municipalidad de Las Condes", "industria": "Municipalidad", "nivel": 3,
        "ubicacion": "RM (Las Condes)", "foco_rm": True,
        "veh_estimados": "Flota municipal + buses de acercamiento", "vans_estimadas": "Decenas (servicios/seguridad)",
        "flota_band": "mediana", "urbano_level": "servicio_urbano_rm", "esg_level": "alto",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "mercado_publico", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Estrategia Energética Local; Sello Comuna Energética Intermedio; cláusula de movilidad sostenible en licitaciones.",
        "compromiso_carbono": "Flota municipal carbono-neutral al 2034.",
        "dolor": "Compromiso vinculante de flota carbono-neutral 2034 con cláusula de movilidad sostenible en sus propias licitaciones.",
        "beneficio_ev48": "Vans EV para servicios comunales (riego, aseo, fiscalización) cumpliendo su meta 2034.",
        "decisores_titulos": ["Dirección de Administración y Finanzas", "Dirección de Medio Ambiente y Aseo", "SECPLA"],
        "senales": ["Flota carbono-neutral 2034 (vinculante)", "10 buses eléctricos de acercamiento", "Motos eléctricas de patrullaje", "Cláusula movilidad sostenible en licitaciones"],
        "fuentes": ["lascondes.cl (buses eléctricos)", "energia.gob.cl (Sello Comuna Energética)"],
        "dato_calidad": "investigado",
        "justificacion": "Comuna con presupuesto, compromiso de flota vinculante y mandato de movilidad sostenible en compras: prospecto público fuerte.",
    },
    {
        "nombre": "Municipalidad de Santiago", "industria": "Municipalidad", "nivel": 3,
        "ubicacion": "RM (Santiago Centro)", "foco_rm": True,
        "veh_estimados": "Flota municipal + expansión seguridad", "vans_estimadas": "Decenas (seguridad/aseo)",
        "flota_band": "pequena", "urbano_level": "servicio_urbano_rm", "esg_level": "medio",
        "fin_level": "media", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "mercado_publico", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Sello Comuna Energética Intermedio; PACES/SECAP (Pacto Global de Alcaldes).",
        "compromiso_carbono": "Aplica PARCC RM (carbono-neutralidad regional 2050).",
        "dolor": "Fuerte expansión de la flota de seguridad (cientos de vehículos por barrio) y precedente de compra EV (2020): demanda creciente de flota liviana.",
        "beneficio_ev48": "Vans EV para patrullaje/fiscalización y aseo, en plena expansión de flota.",
        "decisores_titulos": ["Dirección de Administración y Finanzas / Adquisiciones", "Dirección de Seguridad", "Dirección de Aseo, Ornato y Medio Ambiente"],
        "senales": ["Expansión de flota de seguridad por barrio", "Licitación previa de buses/vehículos EV (2020)", "Convenio marco vehículos ChileCompra disponible"],
        "fuentes": ["munistgo.cl (plan seguridad/flota)", "mercadopublico.cl"],
        "dato_calidad": "investigado",
        "justificacion": "Señal de crecimiento de flota liviana muy fuerte y precedente EV; canal Mercado Público y presupuesto medio moderan velocidad.",
    },
    {
        "nombre": "Municipalidad de Providencia", "industria": "Municipalidad", "nivel": 3,
        "ubicacion": "RM (Providencia)", "foco_rm": True,
        "veh_estimados": "~49 vehículos de seguridad + servicios", "vans_estimadas": "Decenas",
        "flota_band": "pequena", "urbano_level": "servicio_urbano_rm", "esg_level": "alto",
        "fin_level": "media", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "mercado_publico", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "Programa Comuna Energética desde 2015; Estrategia Energética Local; Sello Comuna Energética.",
        "compromiso_carbono": "Meta -50% CO2 al 2030.",
        "dolor": "Flota de seguridad y servicios mayormente a combustión; plan con Enel X reemplazó 1 vehículo por EV (señal unitaria, escalable).",
        "beneficio_ev48": "Escalar el reemplazo EV a la flota de fiscalización/seguridad con vans de bajo TCO.",
        "decisores_titulos": ["Dirección de Administración y Finanzas", "Dirección de Fiscalización", "Dirección de Seguridad Ciudadana", "DAOM"],
        "senales": ["Meta -50% CO2 2030", "Plan EV con Enel X (1 vehículo + carga)", "49 vehículos de seguridad", "Sello Comuna Energética"],
        "fuentes": ["providencia.cl (plan Enel X)", "comunaenergetica.cl/providencia"],
        "dato_calidad": "investigado",
        "justificacion": "Comuna con metas claras y piloto EV iniciado; oportunidad de escalar el reemplazo en flota de seguridad.",
    },
    {
        "nombre": "Municipalidad de Maipú", "industria": "Municipalidad", "nivel": 3,
        "ubicacion": "RM (Maipú)", "foco_rm": True,
        "veh_estimados": "Flota de seguridad ~22 móviles + aseo", "vans_estimadas": "Decenas",
        "flota_band": "pequena", "urbano_level": "servicio_urbano_rm", "esg_level": "medio",
        "fin_level": "media", "adopcion_level": "baja", "acceso_level": "medio",
        "canal_compra": "mercado_publico", "competidor_ev": "parcial", "potencial_elect": "medio",
        "programas_sost": "Sello Comuna Energética Intermedio 2025-2026; EEL 2026-2040; SCAM.",
        "compromiso_carbono": "PACCC e inventario GEI en desarrollo; sin año net-zero explícito.",
        "dolor": "2ª comuna más poblada con flota de seguridad creciente (incluye vans), hoy a combustión.",
        "beneficio_ev48": "Vans EV para seguridad y servicios en una comuna grande con presupuesto comunal.",
        "decisores_titulos": ["Dirección de Administración y Finanzas (Adquisiciones)", "Subdirección de Medio Ambiente", "SECPLA"],
        "senales": ["503.635 hab. (2ª comuna del país)", "4 buses eléctricos de acercamiento", "Plan de seguridad duplicó flota", "Sello Comuna Energética"],
        "fuentes": ["agenciase.org (Sello Comuna Energética)", "comunaenergetica.cl (EEL Maipú)"],
        "dato_calidad": "investigado",
        "justificacion": "Comuna grande con crecimiento de flota; ESG medio y adopción más lenta moderan el score.",
    },

    # ───────────────────── NIVEL 2 — FACILITIES / SERVICIOS ─────────────────────
    {
        "nombre": "Sodexo Chile", "industria": "Facilities / Catering", "nivel": 2,
        "ubicacion": "RM + Nacional (faenas)", "foco_rm": True,
        "veh_estimados": "Flota de servicios/distribución (no pública)", "vans_estimadas": "Decenas",
        "flota_band": "pequena", "urbano_level": "distribucion_mixta", "esg_level": "lider",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Net Zero 2040 (SBTi); 100% electricidad renovable 2025; rating 'A' CDP; WasteWatch.",
        "compromiso_carbono": "Net Zero 2040; -34% CO2 a 2025 (base 2017).",
        "dolor": "Metas SBTi agresivas pero sin programa de flota EV en Chile: greenfield con fuerte presión ESG corporativa.",
        "beneficio_ev48": "Vans EV para distribución de catering y servicios de facilities, cumpliendo sus metas SBTi.",
        "decisores_titulos": ["Gerencia de Operaciones", "Supply Chain / Abastecimiento", "Sostenibilidad / HSEQ", "Gerente Mercado Público"],
        "senales": ["Net Zero 2040 SBTi", "Rating 'A' CDP", "+22.000 colaboradores Chile", "Sin programa EV (greenfield)"],
        "fuentes": ["cl.sodexo.com (compromisos)", "accionempresas.cl (reducción emisiones Sodexo)"],
        "dato_calidad": "investigado",
        "justificacion": "ESG líder con presión SBTi y flota de servicios sin electrificar: greenfield con argumento corporativo fuerte.",
    },
    {
        "nombre": "Aramark Chile", "industria": "Facilities / Catering", "nivel": 2,
        "ubicacion": "RM + Nacional (faenas)", "foco_rm": True,
        "veh_estimados": "Movilidad de servicios (parcial tercerizada)", "vans_estimadas": "Decenas",
        "flota_band": "pequena", "urbano_level": "distribucion_mixta", "esg_level": "alto",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "'Be Well. Do Well.'; Sello HuellaChile; planta con 100% energía renovable.",
        "compromiso_carbono": "-50% emisiones y operación carbono-neutral en 2030; Net Zero 2050.",
        "dolor": "Ya cuantifica y COMPENSA +345.000 km/año de movilidad de servicios (Cabify): argumento directo para electrificar en vez de compensar.",
        "beneficio_ev48": "Sustituir km compensados por flota propia EV con menor TCO: 'deja de compensar, electrifica'.",
        "decisores_titulos": ["Gerencia de Operaciones", "Abastecimiento / Supply Chain", "Sostenibilidad / Medio Ambiente"],
        "senales": ["Meta carbono-neutral 2030", "+345.000 km/año compensados (Cabify)", "Sello HuellaChile", "+23.000 trabajadores Chile"],
        "fuentes": ["infobae.com (Aramark net zero)", "accionempresas.cl (compensación Cabify)"],
        "dato_calidad": "investigado",
        "justificacion": "Meta carbono-neutral 2030 y métrica de km de servicio ya medida: gancho comercial concreto para convertir compensación en flota EV.",
    },

    # ───────────────────── ESTIMACIONES ADICIONALES (validar en Apollo) ─────────────────────
    {
        "nombre": "Lipigas", "industria": "Gas (distribución)", "nivel": 3,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de reparto de cilindros grande", "vans_estimadas": "Decenas-cientos",
        "flota_band": "grande", "urbano_level": "servicio_urbano_rm", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "alto",
        "programas_sost": "Reportes de sostenibilidad; transición energética (estimación, validar).",
        "compromiso_carbono": "Por confirmar.",
        "dolor": "Gran flota de reparto domiciliario de cilindros (recorrido urbano repetitivo) sin programa EV conocido.",
        "beneficio_ev48": "Reparto urbano de cilindros con vans EV de bajo TCO; recorrido repetitivo ideal.",
        "decisores_titulos": ["Gerencia de Operaciones / Logística", "Área de Sostenibilidad"],
        "senales": ["Gran flota de reparto urbano de cilindros", "Empresa abierta en bolsa"],
        "fuentes": [],
        "dato_calidad": "estimacion",
        "justificacion": "Perfil operativo ideal (reparto urbano repetitivo) y respaldo financiero; requiere validación de cifras y ESG en Apollo.",
    },
    {
        "nombre": "Abastible", "industria": "Gas (distribución)", "nivel": 3,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de reparto de cilindros grande", "vans_estimadas": "Decenas-cientos",
        "flota_band": "grande", "urbano_level": "servicio_urbano_rm", "esg_level": "alto",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "parcial", "potencial_elect": "alto",
        "programas_sost": "ESG del Grupo Copec; transición energética (estimación, validar).",
        "compromiso_carbono": "Alineado a Empresas Copec.",
        "dolor": "Gran flota de reparto urbano de cilindros; el respaldo Copec (Voltex) facilita la electrificación.",
        "beneficio_ev48": "Reparto urbano de cilindros con vans EV; sinergia con infraestructura de carga Copec.",
        "decisores_titulos": ["Gerencia de Operaciones / Logística", "Área de Sostenibilidad"],
        "senales": ["Reparto urbano de cilindros a gran escala", "Respaldo Grupo Copec (Voltex)"],
        "fuentes": [],
        "dato_calidad": "estimacion",
        "justificacion": "Igual que Lipigas pero con respaldo Copec/Voltex que sube la facilidad de adopción; validar en Apollo.",
    },
    {
        "nombre": "Cruz Verde", "industria": "Farmacia / Distribución salud", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de reparto a domicilio", "vans_estimadas": "Decenas",
        "flota_band": "mediana", "urbano_level": "ultima_milla_rm", "esg_level": "bajo",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Por confirmar (estimación).",
        "compromiso_carbono": "Por confirmar.",
        "dolor": "Reparto a domicilio de medicamentos en RM (última milla) sin programa EV conocido.",
        "beneficio_ev48": "Última milla farmacéutica urbana con vans EV de bajo TCO; greenfield.",
        "decisores_titulos": ["Gerencia de Operaciones / Logística", "Gerencia de E-commerce"],
        "senales": ["Reparto a domicilio en RM", "Cadena farmacéutica líder (SB)"],
        "fuentes": [],
        "dato_calidad": "estimacion",
        "justificacion": "Última milla urbana clara y greenfield; ESG por validar. Confirmar flota y decisores en Apollo.",
    },
    {
        "nombre": "Salcobrand", "industria": "Farmacia / Distribución salud", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de reparto a domicilio", "vans_estimadas": "Decenas",
        "flota_band": "mediana", "urbano_level": "ultima_milla_rm", "esg_level": "medio",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "ESG del grupo SB (estimación, validar).",
        "compromiso_carbono": "Por confirmar.",
        "dolor": "Reparto a domicilio de medicamentos en RM; sin programa EV conocido.",
        "beneficio_ev48": "Última milla farmacéutica urbana con vans EV; greenfield.",
        "decisores_titulos": ["Gerencia de Operaciones / Logística", "Gerencia de E-commerce / Omnicanal"],
        "senales": ["Reparto a domicilio en RM", "Grupo SB (Empresas SB)"],
        "fuentes": [],
        "dato_calidad": "estimacion",
        "justificacion": "Igual perfil que Cruz Verde; validar flota, ESG y decisores en Apollo.",
    },
    {
        "nombre": "Farmacias Ahumada (FASA)", "industria": "Farmacia / Distribución salud", "nivel": 1,
        "ubicacion": "RM + Nacional", "foco_rm": True,
        "veh_estimados": "Flota de reparto a domicilio", "vans_estimadas": "Decenas",
        "flota_band": "pequena", "urbano_level": "ultima_milla_rm", "esg_level": "bajo",
        "fin_level": "alta", "adopcion_level": "media", "acceso_level": "medio",
        "canal_compra": "venta_directa", "competidor_ev": "ninguno", "potencial_elect": "medio",
        "programas_sost": "Por confirmar (estimación).",
        "compromiso_carbono": "Por confirmar.",
        "dolor": "Reparto a domicilio de medicamentos en RM; sin programa EV conocido.",
        "beneficio_ev48": "Última milla farmacéutica urbana con vans EV; greenfield.",
        "decisores_titulos": ["Gerencia de Operaciones / Logística", "Gerencia de E-commerce"],
        "senales": ["Reparto a domicilio en RM", "Parte de grupo internacional (FEMSA/Casa Saba histórico)"],
        "fuentes": [],
        "dato_calidad": "estimacion",
        "justificacion": "Última milla urbana; menor escala estimada que Cruz Verde/Salcobrand. Validar en Apollo.",
    },
]
