[theme]
primaryColor = "#009406"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#161616"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
